#!/usr/bin/env bash

usage() {
    echo "Usage: $0 [--profile <aws-profile-name>] [--query '<JMESPath Query>']"
    echo "Note: If --profile not used, default aws profile will be used."
    echo "Example: $0 --profile myawsprofile --query 'Buckets[].Name'"
}

# Help
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

# Defaults
PROFILE_NAME="default"
QUERY=""

# Parse arguments
# While number of arguments greater than zero
# check for profile or query flags, and read the flag + value, then shift rest of arguments down 2 positions.
while [[ $# -gt 0 ]]; do
  case "$1" in
    "--profile")
      [[ -n "${2:-}" || "$2" == --* ]] || { echo "Error: --profile requires a value."; exit 1; }
      PROFILE_NAME="$2"
      check_profile=$(aws configure list-profiles | grep -Fx "$PROFILE_NAME")
      if [ -z "$check_profile" ]; then
        echo "Error: AWS Profile not configured! (profile name: $PROFILE_NAME)"
        exit 1
      fi
      shift 2
      ;;
    "--query")
      [[ -n "${2:-}" || "$2" == --* ]] || { echo "Error: --query requires a value."; exit 1; }
      QUERY="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

# Build aws API call
if [[ -n "$QUERY" ]]; then
    result=$(aws s3api list-buckets --profile "$PROFILE_NAME" --query "$QUERY" --output json)
    if [ "$result" == "null" ]; then
        echo "Returned result is null, either non found or invalid query."
        echo "Your query was: $QUERY"
        exit 0
    fi
    echo "$result"
    exit 0
else
    aws s3api list-buckets --profile "$PROFILE_NAME" --output json
    exit 0
fi